import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { SidebarProvider } from "@/components/providers/SidebarProvider";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <SidebarProvider>
        <div className="h-full">{children}</div>
     </SidebarProvider>   
    <SanityLive />
    </ClerkProvider>
  );
}


